# Generated by Django 3.2.14 on 2022-09-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Pending', max_length=200, null=True),
        ),
    ]
