# Generated by Django 3.2.14 on 2022-09-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
